<!----- PHP DEFINITIONS ------>
<?php
    require_once "webpage.php";
    session_start(); // must be included for stored session variables to work

    class Index extends Webpage{
        /**
        * Generates a new movie. If the user is signed in, only movies not in the watched list are generated.
        * Otherwise any random movie is generated.
        */
        public function GenerateNewMovie(){
            //if user is signed in, get a random movie not in the user's watched list
            if( isset($_SESSION["id"]) ){
                $sql = "SELECT *
                    FROM movie m
                    LEFT JOIN user_movie um ON um.um_movie = m.id AND um.um_user = ?
                    WHERE um.um_movie IS NULL
                    ORDER BY RAND()
                ";
                $stmt = $this->pdo->prepare($sql);
                $stmt->execute( [$_SESSION["id"]] );
            }
            // else just display a random movie, since no user is signed in
            else{
                $sql = "SELECT * FROM movie ORDER BY RAND()";
                $stmt = $this->pdo->prepare($sql);
                $stmt->execute();
            }
            
            // no movies exist in database or no new movies to display to signed-in user
            if($stmt->rowCount() < 1){
                echo "<p>No more movies to display.</p>";
                return;
            }

            // get the randomly generated movie data
            $row = $stmt->fetch();
            // keep getting a random movie until it is not the same one that was generated last time.
            // only if there are 2 or more movies of possible movies to show
            while($stmt->rowCount() >= 2 && isset($_COOKIE["currentMovie"]) && $row['ID'] == $_COOKIE["currentMovie"]){
                $row = $stmt->fetch();
            }

            $this->DisplayMovie($row);
            
        }

        /**
        * Queryies for the movie that was previously generated. This is so if the user refreshes the page, the movie last generated is not
        * lost. Uses a cookie to track the movie's id. If the user has not previously generated a movie, then call the function to generate
        * a new movie instead and exit this function
        */
        public function GeneratePreviousMovie(){
            // if the cookie tracking the last movie is not present, we must generate a new movie as we have no previous movie to reference
            if(!isset($_COOKIE["currentMovie"]))
                {
                    $this->GenerateNewMovie();
                    return;
                }

            //populate page with data of the movie that was last generated by querying for the last movie generated
            $sql = "SELECT * FROM movie WHERE id = ?";
            $stmt = $this->pdo->prepare($sql);
            $stmt->execute([ $_COOKIE["currentMovie"] ]);

            $row = $stmt->fetch();

            $this->DisplayMovie($row);
            
        }

        /**
        * Displays the movie information and related buttons to the user.
        *
        * param $row:  is an array of the row or record result from executing the query for a generating a movie. 
        */
        private function DisplayMovie($row){
            //get the movies' fields and set them equal to variables.
            $id = $row['ID'];

            setcookie("currentMovie", $id);

            $title = $row['Title'];
            $year = $row['Year'];
            $genre = $row['Genre'];
            $rating = $row['IMDb Rating'];
            $description = $row['Description'];

            //display the fields to the user
            echo "
                <h2 class='d-flex justify-content-center'> $title </h2>
                <p> <b>Year:</b> $year </p>
                <p> <b>Genre:</b> $genre </p>
                <p> <b>IMDb Rating:</b> $rating </p>
                <p> <b>Description:</b> $description </p>
            ";

            //if user is logged in and if movie is in the user's watched list, display a message
            // otherwise display a button which allows the user to add the movie to their watched list
            if( isset($_SESSION["loggedin"]) && $_SESSION["loggedin"] == true){
                //query to see if movie is in watched list
                $sql = " SELECT u.*, m.*
                    FROM user u
                    INNER JOIN user_movie um
                    ON um.um_user = u.id
                    INNER JOIN movie m
                    ON m.id = um.um_movie
                    WHERE u.id = ? AND m.id = ?
                ";
                $stmt = $this->pdo->prepare($sql);
                $stmt->execute([ $_SESSION["id"], $id ]);


                //if in watched list, display message
                if ($stmt->rowCount() == 1) {
                    echo "<p class='lead mt-3' style='color: green;'>Added to watch list.</p>";
                }
                //otherwise draw a button with functionality to add to the watched list
                else {
                    // works with AJAX
                    echo "
                        <form method='post'>
                            <button class='btn btn-success mr-1 rowButton' type='button' name='movieIDToAdd' value='$id'>Add to watched list</button>
                        </form>
                    ";

                    echo"
                        <p class='lead mt-3 addedText' style='display: none; color: green;'>Added to watch list.</p>
                    ";
                }
            }
        }

        public function LogOut(){
            // Unset all of the session variables
            $_SESSION = array();
            
            // Destroy the session.
            session_destroy();
            
        }

    }

    $index = new Index();

    if( isset($_POST["logOut"]) )
        $index->LogOut();
?>



<!----- HTML ------>

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Home</title>
    
    <!-- import bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    
    <!-- import jquery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    
	<link href="index.css" rel="stylesheet">

    <script>
        //uses AJAX to call php to add row
        $(document).ready(function() {
	        $('.rowButton').on('click', function() {
                $(this).remove();
                $('.addedText').show();

                
                $.ajax({
                    url: "pages/update_watched_list.php",
                    type: "POST",
                    data: {
                        movieIDToAdd: $(this).val()
                    },
                    success: function(){},
                    error:function (){}
                    
                });
                
            });
        });
    </script>

</head>
<body>


<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">

    <a class="navbar-brand" href="index.php" >FINAL PROJECT - Random Movie Generator</a>

    <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
        <button type="submit" class="btn btn-success mr-1" name="generateMovie" value="True">GENERATE</button>
    </form>

    <div class="navbar-nav ml-auto">
        <?php
            // if the user is NOT logged in, then display a sign in button
            if(!isset($_SESSION["loggedin"]) || $_SESSION["loggedin"] !== true){
                echo "<button onclick='document.location=\"pages/sign_in.php\"' class='btn btn-primary mr-1'>Sign in/Sign up</button>";
            }
            // else display the username as well as a log out button
            if(isset($_SESSION["loggedin"]) && $_SESSION["loggedin"] == true){
                $username = $_SESSION['username'];
                echo "
                    <p class='lead mt-1 mr-2'>Welcome, <a href='pages/user_preferences.php'>$username</a> </p>
                ";

                echo "
                    <form action='index.php' method='post'>
                        <button type='submit' name='logOut' value='true' class='btn btn-danger mr-1'>Logout</button>
                    </form>
                ";
            }
        ?>
    </div>

</nav>


<!--- Movie details Section -->
<hr class="my-4">
    <div class="container">
      
    <?php
        // generate a new movie if the generate button was pressed
        if( isset($_POST["generateMovie"]) )
            $index->GenerateNewMovie();
        //otherwise load the last movie generated if its cookie exists
        else
            $index->GeneratePreviousMovie();
    ?>

    <script>
        //prevents refreshing and duplicate form submissions
        if ( window.history.replaceState ) {
            window.history.replaceState( null, null, window.location.href );
        }
    </script>
</div>
<hr class="my-4">


<!--- Footer -->
<footer class="fixed-bottom">
    <div class="container-fluid padding">
        <p class="text-center">Heriberto Flores</p>
        <p class="text-center">INF 653</p>
        <p class="text-center">h_flores@fhsu.mail.edu</p>
    </div>
</footer>

</body>
</html>